services:
  backend:
    build: .
    ports:
      - "4000:4000"  
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: postgres  
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"  
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4  
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com  
      PGADMIN_DEFAULT_PASSWORD: admin        
    ports:
      - "5050:80"  
    networks:
      - app-network

networks:
  app-network:
    driver: bridge  
