services:
  backend:
    build: .
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgres://mydb_d71p_user:mU4u5tHPjKGKHqGjONALS8fSBXXbcecH@dpg-csbi033tq21c73a0pq60-a.oregon-postgres.render.com/mydb_d71p  # Conexión a la base de datos de Render
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
